// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Clientes
{
    public int IdCliente { get; set; }

    public string Nombre { get; set; }

    public string TipoIdentificacion { get; set; }

    public string Identificacion { get; set; }

    public string Telefono { get; set; }

    public string Email { get; set; }

    public string Direccion { get; set; }

    public double? Latitud { get; set; }

    public double? Longitud { get; set; }

    public int IdCategoriaCliente { get; set; }

    public int? IdZonaGeografica { get; set; }

    public string Estado { get; set; }

    public bool EsEliminado { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public string CreadoPor { get; set; }

    public string ModificadoPor { get; set; }

    public virtual CategoriasClientes IdCategoriaClienteNavigation { get; set; }

    public virtual ZonasGeograficas IdZonaGeograficaNavigation { get; set; }

    public virtual ICollection<Pedidos> Pedidos { get; set; } = new List<Pedidos>();
}