// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Inventarios
{
    public int IdInventario { get; set; }

    public int IdPuntoVenta { get; set; }

    public int IdProducto { get; set; }

    public int CantidadDisponible { get; set; }

    public bool EsEliminado { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public string CreadoPor { get; set; }

    public string ModificadoPor { get; set; }

    public virtual Productos IdProductoNavigation { get; set; }

    public virtual PuntosVenta IdPuntoVentaNavigation { get; set; }
}