// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Pedidos
{
    public int IdPedido { get; set; }

    public int IdCliente { get; set; }

    public int IdPuntoVenta { get; set; }

    public DateTime FechaPedido { get; set; }

    public string Estado { get; set; }

    public bool EsEliminado { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public string CreadoPor { get; set; }

    public string ModificadoPor { get; set; }

    public virtual ICollection<DetallesPedidos> DetallesPedidos { get; set; } = new List<DetallesPedidos>();

    public virtual Clientes IdClienteNavigation { get; set; }

    public virtual PuntosVenta IdPuntoVentaNavigation { get; set; }
}