// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Productos
{
    public int IdProducto { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public decimal PrecioUnitario { get; set; }

    public int IdCategoriaProducto { get; set; }

    public bool Activo { get; set; }

    public bool EsEliminado { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public string CreadoPor { get; set; }

    public string ModificadoPor { get; set; }

    public virtual ICollection<DetallesPedidos> DetallesPedidos { get; set; } = new List<DetallesPedidos>();

    public virtual CategoriasProductos IdCategoriaProductoNavigation { get; set; }

    public virtual ICollection<Inventarios> Inventarios { get; set; } = new List<Inventarios>();
}