// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Usuarios
{
    public int IdUsuario { get; set; }

    public string NombreUsuario { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public int IdRol { get; set; }

    public string Estado { get; set; }

    public bool EsEliminado { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public string CreadoPor { get; set; }

    public string ModificadoPor { get; set; }

    [JsonIgnore]
    public virtual Roles IdRolNavigation { get; set; }
}