// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class ZonasGeograficas
{
    public int IdZonaGeografica { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public string Coordenadas { get; set; }

    public string Estado { get; set; }

    public bool EsEliminado { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public string CreadoPor { get; set; }

    public string ModificadoPor { get; set; }

    public virtual ICollection<Clientes> Clientes { get; set; } = new List<Clientes>();

    public virtual ICollection<PuntosVenta> PuntosVenta { get; set; } = new List<PuntosVenta>();
}